/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {


  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData users = IconData(0xf0c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_clock = IconData(0xf4fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_friends = IconData(0xf500, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_lock = IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_shield = IconData(0xf505, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heater_svgrepo_com = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooler_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData washing_machine_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refrigerator_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
